from pydantic import BaseModel, Field
from typing import List, Optional
from datetime import datetime


class ProductSummary(BaseModel):

    total_revenue: float = Field(
        ...,
        description="Total revenue generated by all products in the selected time range.",
    )

    total_quantity_sold: int = Field(
        ..., description="Total number of units sold across all products."
    )

    top_product_count: int = Field(
        ..., description="Number of top products included in the report."
    )

    date_range_days: int = Field(
        ..., description="Total number of days in the selected date range."
    )


class ProductPerformanceItemModel(BaseModel):

    product_id: str = Field(..., description="Unique identifier of the product.")

    product_name: str = Field(..., description="Name of the product.")

    category: str = Field(..., description="Category of the product.")

    total_quantity_sold: int = Field(
        ..., description="Total number of units sold for this product."
    )

    total_revenue: float = Field(
        ..., description="Total revenue generated by this product."
    )

    number_of_orders: int = Field(
        ..., description="Number of orders that included this product."
    )

    average_order_quantity: float = Field(
        ..., description="Average number of units sold per order for this product."
    )


class CategoryPerformanceModel(BaseModel):

    category: str = Field(..., description="Category name.")

    total_quantity: int = Field(
        ..., description="Total quantity of products sold in this category."
    )

    total_revenue: float = Field(
        ..., description="Total revenue generated by this category."
    )

    unique_products: int = Field(
        ..., description="Number of unique products in this category."
    )


class ProductInsight(BaseModel):

    top_product: Optional[str] = Field(
        None, description="Product with the highest revenue."
    )

    top_category: Optional[str] = Field(
        None, description="Category with the highest revenue."
    )

    highest_demand_product: Optional[str] = Field(
        None, description="Product with the highest quantity sold."
    )

    performance_trend: str = Field(
        ..., description="Overall product performance trend: strong, moderate, or weak."
    )

    recommendation: str = Field(
        ...,
        description="Actionable recommendation such as promoting top products or improving low-performing ones.",
    )


class ProductPerformanceAgentResponse(BaseModel):

    report_type: str = Field(
        ..., description="Type of analytics report. Always 'PRODUCT_PERFORMANCE'."
    )

    start_date: datetime = Field(..., description="Start date of the report.")

    end_date: datetime = Field(..., description="End date of the report.")

    summary: ProductSummary = Field(
        ..., description="Overall product performance summary."
    )

    top_products: List[ProductPerformanceItemModel] = Field(
        ..., description="List of top performing products."
    )

    category_performance: List[CategoryPerformanceModel] = Field(
        ..., description="Category-wise aggregated performance data."
    )

    insights: ProductInsight = Field(
        ..., description="AI-generated insights about product and category performance."
    )

    natural_language_summary: str = Field(
        ...,
        description="Human-readable explanation summarizing key product performance insights.",
    )
