from pydantic import BaseModel, Field
from typing import List, Optional
from datetime import datetime


class SalesSummary(BaseModel):
    total_sales: int = Field(
        ...,
        description="Total number of completed sales transactions within the requested date range.",
    )

    total_revenue: float = Field(
        ...,
        description="Total revenue generated from all sales during the selected period.",
    )

    total_quantity: int = Field(
        ...,
        description="Total number of product units sold across all sales transactions.",
    )

    average_sale_value: float = Field(
        ...,
        description="Average monetary value of a single sale transaction. Calculated as total_revenue divided by total_sales.",
    )


class SalesTrendItem(BaseModel):
    period: str = Field(
        ...,
        description="Time period for the aggregated sales data. Format depends on grouping (day, week, or month).",
    )

    total_sales: int = Field(
        ...,
        description="Number of sales transactions that occurred within this time period.",
    )

    total_revenue: float = Field(
        ..., description="Total revenue generated during this specific time period."
    )

    total_quantity: int = Field(
        ..., description="Total number of product units sold during this time period."
    )


class ProductPerformance(BaseModel):
    product_id: str = Field(..., description="Unique identifier of the product.")

    product_name: str = Field(..., description="Human-readable name of the product.")

    quantity_sold: int = Field(
        ...,
        description="Total number of units sold for this product within the selected date range.",
    )

    revenue: float = Field(..., description="Total revenue generated by this product.")

    sales_count: int = Field(
        ...,
        description="Number of individual sales transactions that included this product.",
    )


class CategoryPerformance(BaseModel):
    category: str = Field(
        ..., description="Product category name used to group sales data."
    )

    quantity_sold: int = Field(
        ..., description="Total quantity of products sold in this category."
    )

    revenue: float = Field(..., description="Total revenue generated by this category.")

    sales_count: int = Field(
        ...,
        description="Total number of sales transactions involving products from this category.",
    )


class SalesInsight(BaseModel):
    top_product: Optional[str] = Field(
        None,
        description="Name of the product that generated the highest revenue during the selected period.",
    )

    top_category: Optional[str] = Field(
        None, description="Category that generated the highest total revenue."
    )

    highest_revenue_period: Optional[str] = Field(
        None,
        description="Time period (day/week/month) where the highest revenue was recorded.",
    )

    revenue_trend: str = Field(
        ...,
        description="Overall revenue trend across the time range. Possible values: increasing, decreasing, or stable.",
    )


class SalesAnalyticsAgentResponse(BaseModel):

    report_type: str = Field(
        ...,
        description="Type of analytics report generated. Always 'SALES' for this agent.",
    )

    start_date: datetime = Field(
        ..., description="Start date of the analytics report time range."
    )

    end_date: datetime = Field(
        ..., description="End date of the analytics report time range."
    )

    summary: SalesSummary = Field(
        ...,
        description="Overall sales performance summary for the selected date range.",
    )

    trend: List[SalesTrendItem] = Field(
        ...,
        description="Time-series sales performance grouped by the selected time interval (day, week, or month).",
    )

    product_breakdown: List[ProductPerformance] = Field(
        ...,
        description="Detailed breakdown of sales performance by individual products.",
    )

    category_breakdown: List[CategoryPerformance] = Field(
        ...,
        description="Detailed breakdown of sales performance by product categories.",
    )

    insights: SalesInsight = Field(
        ...,
        description="AI-generated business insights derived from the sales analytics data.",
    )

    query_parameters: dict = Field(
        ...,
        description="Parameters used to generate this report including start_date, end_date, product_id, category, and group_by.",
    )

    natural_language_summary: str = Field(
        ...,
        description="Human-readable explanation summarizing the key findings from the sales analytics report.",
    )
